#!/usr/bin/env zsh

cd repos/ours

# js
find . -name package.json \
  | grep -v sentry-docs/src/gatsby \
  | sed -e 's|\./\(.*\)|\1|' \
  > ../../eco/js/deps-files

# py
find . -name \*requirements\*.txt \
  | sed -e 's|\./\(.*\)|\1|' \
  > ../../eco/py/deps-files

# rs
find . -name Cargo.toml \
  | sed -e 's|\./\(.*\)|\1|' \
  > ../../eco/rs/deps-files
