#!/usr/bin/env python3
import csv
import json
import os
import subprocess

github = json.load(open('github.json'))

os.makedirs('gh', exist_ok=True)

for eco in github:
    for org in github[eco]:
        for repo in github[eco][org]:
            if repo.endswith('.git'):
                raise Heck  # this is supposed to be filtered out in lib.js > dereference
            filepath = f'gh/{org}-{repo}.json'
            if os.path.exists(filepath):
                print(f'have {org}/{repo}')
                continue
            query = f'query {{ repository(owner: \"{org}\", name: \"{repo}\") {{ fundingLinks {{ platform url }} stargazerCount }} }}'
            body = json.dumps({"query": query}).encode()
            out, err = subprocess.Popen(
                ['gh', 'api', 'graphql', '--input', '-'],
                stdin=subprocess.PIPE,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            ).communicate(body)
            assert not err, err
            json.dump(json.loads(out), open(filepath, 'w+'), indent=2)
            print(f'got  {org}/{repo}')
