#!/usr/bin/env python3
import csv
import json

github = json.load(open('github.json'))
out = csv.writer(open('deps.csv', 'w'))


def get_url(deets):
    url = slug = ''
    have_github = False
    for link in deets['fundingLinks']:
        if link['platform'] == 'GITHUB':
            if have_github:
                continue
            have_github = True
            # link['url'] is not the sponsors URL
            slug = link['url'].split('/')[-1]
            url = f'https://github.com/sponsors/{slug}'
        elif link['platform'] == 'OPEN_COLLECTIVE':
            if 'unified' in link['url']:
                # special case because we have two projects of theirs
                # one of which has GH + OC the other has OC only
                url = 'https://github.com/sponsors/unifiedjs'
                slug = 'unifiedjs'
                break
            elif have_github:
                print(f"also on OC: {link['url']}")
                continue
            else:
                url = link['url']
                slug = url.split('/')[-1]
    return url, slug


for eco in github:
    for org in github[eco]:
        for repo in github[eco][org]:
            deets = json.load(open(f'gh/{org}-{repo}.json'))['data']['repository']
            if org == 'psf':  # special case
                url, sponsorable = ('https://www.python.org/psf/donations/', 'psf')
            else:
                url, sponsorable = get_url(deets)
            if url:
                if sponsorable in ['getsentry', 'mitsuhiko', 'jan-auer', 'asottile']:
                    # Special case filter out Sentry + staff. Ril WET.
                    continue
                out.writerow([org, sponsorable, url, repo, deets['stargazerCount'], eco])
