#!/usr/bin/env python3
import csv
import json

github = json.load(open('github.json'))
out = csv.writer(open('deps.csv', 'w'))


def get_url(org, deets):
    url = ''
    for link in deets['fundingLinks']:
        if link['platform'] == 'GITHUB':
            url = f'https://github.com/sponsors/{org}'
            # link['url'] is not the sponsors URL
            break
        elif link['platform'] == 'OPEN_COLLECTIVE':
            url = link['url']
    return url


for eco in github:
    for org in github[eco]:
        for repo in github[eco][org]:
            deets = json.load(open(f'gh/{org}-{repo}.json'))['data']['repository']
            url = get_url(org, deets)
            if url:
                out.writerow([org, url, repo, deets['stargazerCount'], eco])
