#!/usr/bin/env python3
import csv
import json

github = json.load(open('github.json'))
out = csv.writer(open('deps.csv', 'w'))


def get_url(deets):
    url = slug = ''
    for link in deets['fundingLinks']:
        if link['platform'] == 'GITHUB':
            # link['url'] is not the sponsors URL
            slug = link['url'].split('/')[-1]
            url = f'https://github.com/sponsors/{slug}'
            break
        elif link['platform'] == 'OPEN_COLLECTIVE':
            url = link['url']
            slug = url.split('/')[-1]
    return url, slug


for eco in github:
    for org in github[eco]:
        for repo in github[eco][org]:
            deets = json.load(open(f'gh/{org}-{repo}.json'))['data']['repository']
            if org == 'psf':  # special case
                url, sponsorable = ('https://www.python.org/psf/donations/', 'psf')
            else:
                url, sponsorable = get_url(deets)
            if url:
                out.writerow([org, sponsorable, url, repo, deets['stargazerCount'], eco])
